// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-rrlXlPN9K9AtK_29Owf3EQYnuv2XNwg',
    appId: '1:650351174300:web:0571fc70358aa39d328359',
    messagingSenderId: '650351174300',
    projectId: 'graduation-9d9e5',
    authDomain: 'graduation-9d9e5.firebaseapp.com',
    storageBucket: 'graduation-9d9e5.firebasestorage.app',
    measurementId: 'G-HLD9C2KEVM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAoBnWRbHnSvAJjfK7Qvq3y1DyDKevaHQ',
    appId: '1:650351174300:android:74b8574eeb6d573e328359',
    messagingSenderId: '650351174300',
    projectId: 'graduation-9d9e5',
    storageBucket: 'graduation-9d9e5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7wSL3ZklEQ8AyOK2KZJKJF5ZdLEviaws',
    appId: '1:650351174300:ios:8b4dd24942a38e55328359',
    messagingSenderId: '650351174300',
    projectId: 'graduation-9d9e5',
    storageBucket: 'graduation-9d9e5.firebasestorage.app',
    iosBundleId: 'com.example.graduationAppAssistant',
  );
}
